version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: coresupport_postgres
    restart: unless-stopped
    env_file:
      # Читаем переменные для создания БД прямо из .env файла
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - coresupport_pg_data:/var/lib/postgresql/data

  backend:
    build: .  # Говорит докеру: "собери образ из Dockerfile в этой же папке"
    container_name: coresupport_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      - db

volumes:
  coresupport_pg_data: